/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Cartesian2: typeof import('cesium')['Cartesian2']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Cartesian2 as TCartesian2, Cartesian3 } from 'cesium'
  import('cesium')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly Cartesian2: UnwrapRef<typeof import('cesium')['Cartesian2']>
  }
}
declare module '@vue/runtime-core' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly Cartesian2: UnwrapRef<typeof import('cesium')['Cartesian2']>
  }
}
